{% set name = "reentry" %}
{% set version = "1.3.2" %}
{% set sha256 = "0b609d2c14f9cc47a8a0a51e398f426510ecee4d0d3d32ef0bc36dda27c23bd5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/DropD/reentry/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reentry = reentry.cli:reentry
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - six
    - pathlib2  # [py < 35]

test:
  imports:
    - reentry
  source_files:
    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin manager based on setuptools entry points mechanism
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
    - DropD
    - chrisjsewell
