{% set name = "reentry" %}
{% set version = "1.1.1" %}
{% set sha256 = "70924e8fbbbab75a823ce8d01c88773a1be30596e385370b85c25cd1f9c71d97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reentry = reentry.cli:reentry
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not py27]

requirements:
  build:
    - python
    - setuptools >=18.5

  host:
    - pip

  run:
    - python
    - click

test:
  imports:
    - reentry
  commands:
    - reentry --help
    - python -m pytest
  requires:
    - packaging
    - pytest-cov
    - coverage
    - pytest
    - flake8
    - pylint
  source_files:
    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A plugin manager based on setuptools entry points mechanism'
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
