{% set name = "reentry" %}
{% set version = "1.3.1" %}
{% set sha256 = "641a8130a7018983a10c67877ab068c823c2af02e429684ecec9c1d53c6a8e87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/DropD/reentry/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  entry_points:
    - reentry = reentry.cli:reentry
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - six
    - pathlib2  # [py < 35]

test:
  imports:
    - reentry
  source_files:
    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A plugin manager based on setuptools entry points mechanism'
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
    - DropD
    - chrisjsewell
