{% set name = "reentry" %}
{% set version = "1.2.1" %}
{% set sha256 = "bde45202b6781e5fc1acfe837e9142f17da69140ff62f327159407f6c7d8a542" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reentry = reentry.cli:reentry
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not py27]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - six
    - py

test:
  imports:
    - reentry
  source_files:
    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A plugin manager based on setuptools entry points mechanism'
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
