{% set name = "reentry" %}
{% set version = "1.2.0" %}
{% set sha256 = "00df980d8c61713f5002d4d893ba6ea38e9a721cd04aef5a520b974e700ab550" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  entry_points:
    - reentry = reentry.cli:reentry
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not py27]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - six
    - py

# tests disabled until #28 fixed
# https://github.com/DropD/reentry/issues/28
#test:
#  imports:
#    - reentry
#  source_files:
#    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A plugin manager based on setuptools entry points mechanism'
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
