{% set name = "reentry" %}
{% set version = "1.1.0"%}
{% set sha256 = "8c234a14d74715b0ed2cc905ca0b3ecfa9af3844cc2f7843a47f2bb681d03716"%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reentry = reentry.cli:reentry
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [not py27]

requirements:
  build:
    - python
    - setuptools >=18.5
  run:
    - python
    - click

test:
  imports:
    - reentry
  commands:
    - reentry --help
    - python -m pytest
  requires:
    - pytest
  source_files:
    - reentry

about:
  home: https://github.com/DropD/reentry
  license: MIT
  license_family: MIT
  # PR for including license file: https://github.com/DropD/reentry/pull/10
  #license_file: LICENSE
  summary: 'A plugin manager based on setuptools entry points mechanism'
  dev_url: https://github.com/DropD/reentry

extra:
  recipe-maintainers:
    - ltalirz
