appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: zxl31aaVXrvbt2mFqycy62ayZxyy3Pth39DQJVZjkbOaWsB9hokJmEcJLPcR9XDEpBVkDs4PE500655070DRa7GCQ9bP3I0af3Se/FSZOvky4t5GjXl4gvzXcxCI2oqiFZdmzQFfEhAGqI0L2AyF5rAsuqXfSkzyrRyjxeJnAjm34WQLVQKfvhmZZVVgv1lJTpR4TPNGbbBp08uRUgHoO+jcqmboDweOngTybK0WQ7+7p4iDWaQxdYOIT9XAnZgqe6qsKazCuoCfUN30f+CV1iX9+uPhgU3ttt1pksN09IFe+mXFiOdc7atvvO9QoaGgBcSsQwrKhPFrBvYrPcrAfSQKd++R/KVGmU2ae6dPZwxNV4CjPNc5+NJS4mlIK3N2Y5vxi19n+pEorLEpPsh/pY22msjFFEQRM4chJxQAGaMCuj5ibGTUncDA7RRVbn+VpDcfMNAJ8dPwRvlvKsMgw89EvT817f1I5OQ2eA94haujWDFN0g0HsGyvwjazzJ5Xt07fCoa2fQ/iBoJDNfShn4qoX8tVEOfy13sff5NhKp11LAOEeSquPmv/dVv3fwqA9O8sOlvsYZ85O3sSg2ob4K3GaauwfmLpKh9WMvU95Hsh6THHvxtrI3eelobzw6dhqmDgo6H7/UQbsvwQ3SekvdpTfyCAZD0EIzX85ba2c48=}
provider:
  win: azure
conda_forge_output_validation: true
