travis:
  secure:
    BINSTAR_TOKEN: yDtiTg3V3dJSt2/L4NLW2bc77Z4tIDfFVm7IoPzfP1OYqtiTiRni3hdh/rNJWzwlSDPk8X6esR+hMTAb1RrNKP3L19O1o4sarzflrS1IZol/3zp6exlI5VUpfCj6JbRdXLUCVGAI3Y5AjbqyIftmtnTwicUtdhRGOrLn3AnpYXC6J3tSs0v+elmkj4/KK62r/FVAtJ7FCj9g3m2awdeJY8U7dRq5qupXLncZDcpK77/R/PIi/IR1E9XyCjFBhsUQq9fRkXvMAJ1WB5vDNCOWxFwcbUHj/AZ0QyoiUfmgmpgNJvwQU91aHGxubdycsNOIvpuzBrK0FZxuy4tINSscsxs4OTQNqUyT7yquUKDK+b9Kp/phD94ortv/Ut0S0PqmFRT7wZtvu722J/9ylmVar/jA1ZaJzjTtBnB/+PwKtgp/9Ht66OkcpD7DUq3cAl4c8w2CW4pTw2dj7YNVo+Prfk4aOt43OWET7kKNJrYrSJltnRe7SDKXzbqM0I00vNo/60K16HiTDjLmPq4gwkd2ojxweDKnWVEypyRHAesaSJfc99inGAW6QKV9AHjuxm4DQXUXekwv0/nMaJzvIObDLVY/QjnMGhkqhA1XZH36Vt4Xeey0iY6qFewFZlQt2Z0HxEQjXxEM+1c0fm85y1el0igfNOGmwjj+D0EZVPCh3Lo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
